---

version: '2.4'

services:
  ui:
    image: docker.io/kubesealwebgui/ui:4.2.2
    build:
      context: .
      dockerfile: Dockerfile.ui
    restart: 'on-failure'
    depends_on:
      - api
    networks:
      - app
    ports:
      - '127.0.0.1:8080:8080'
    environment:
      API_HOST: api
      PUBLIC_HOST: 127.0.0.1
  api:
    image: docker.io/kubesealwebgui/api:4.2.2
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: 'on-failure'
    networks:
      - app
    ports:
      - '127.0.0.1:5000:5000'
    volumes:
      - type: bind
        source: ./api/kubeseal_webgui_api
        target: /kubeseal-webgui/lib/python3.10/site-packages/kubeseal_webgui_api
        read_only: true
    environment:
      ORIGIN_URL: 'http://127.0.0.1:5000/'
      MOCK_ENABLED: "True"
      MOCK_NAMESPACE_COUNT: "10"

networks:
  app:
