---

version: '2.4'

services:
  ui:
    image: docker.io/kubesealwebgui/ui
    build:
      context: .
      dockerfile: Dockerfile.ui
    restart: 'on-failure'
    depends_on:
      - api
    networks:
      - app
    ports:
      - '127.0.0.1:8080:8080'
    environment:
      API_HOST: api
      PUBLIC_HOST: 127.0.0.1
  api:
    image: docker.io/kubesealwebgui/api
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: 'on-failure'
    networks:
      - app
#    ports:
#      - '127.0.0.1:5000:5000'
#    volumes:
#      - './api/kubeseal_webgui_api:/kubeseal-webgui/lib/python3.9/site-packages/kubeseal_webgui_api:ro'
    environment:
      MOCK_ENABLED: 'true'
      K8S_NAMESPACE_RESOURCE: pod

networks:
  app:
