{{- $ingress := .Values.ui.ingress | default .Values.ingress -}}
{{- if $ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kubeseal-webgui.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubeseal-webgui.labels" . | nindent 4 }}
  {{- if $ingress.annotations }}
  annotations:
    {{- range $key, $value := $ingress.annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}
spec:
{{- if $ingress.ingressClassName }}
  ingressClassName: {{ $ingress.ingressClassName }}
{{- end }}
{{- if $ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ $ingress.hostname }}
    secretName: {{ $ingress.tls.secretName }}
{{- end }}
  rules:
  - host: {{ $ingress.hostname }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "kubeseal-webgui.fullname" . }}
            port:
              number: 8080
        path: /
        pathType: Prefix
{{- end }}
