{{- if .Values.ui.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kubeseal-webgui.fullname" . }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubeseal-webgui.labels" . | nindent 4 }}
  {{- if .Values.ui.ingress.annotations }}
  annotations:
    {{- range $key, $value := .Values.ui.ingress.annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}
spec:
{{- if .Values.ui.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ui.ingress.ingressClassName }}
{{- end }}
{{- if .Values.ui.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.ui.ingress.hostname }}
    secretName: {{ .Values.ui.ingress.tls.secretName }}
{{- end }}
  rules:
  - host: {{ .Values.ui.ingress.hostname }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "kubeseal-webgui.fullname" . }}-ui
            port:
              number: 8080
        path: /
        pathType: Prefix
{{- end }}