{{- $route := .Values.ui.route | default .Values.route -}}
{{- if $route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "kubeseal-webgui.fullname" . }}
  labels:
    {{- include "kubeseal-webgui.labels" . | nindent 4 }}
{{- with $route.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if $route.hostname }}
  host: {{ $route.hostname | quote }}
{{- end }}
  to:
    kind: Service
    name: {{ include "kubeseal-webgui.fullname" . }}
    weight: 100
  port:
    targetPort: ui
  {{- if $route.tls.enabled }}
  tls:
    termination: {{ $route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ $route.tls.insecureEdgeTerminationPolicy }}
  {{- end }}
  wildcardPolicy: None
{{- end }}
