
{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "kubeseal-webgui.fullname" . }}
  labels:
    {{- include "kubeseal-webgui.labels" . | nindent 4 }}
{{- with .Values.route.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.route.hostname }}
  host: {{ .Values.route.hostname | quote }}
{{- end }}
  to:
    kind: Service
    name: {{ include "kubeseal-webgui.fullname" . }}
    weight: 100
  port:
    targetPort: ui
  tls:
    termination: {{ .Values.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy }}
  wildcardPolicy: None
{{- end }}
