apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeseal-webgui.fullname" . }}
  labels:
    {{- include "kubeseal-webgui.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ template "kubeseal-webgui.name" . }}
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: ui
      protocol: TCP
      name: ui
