{{- if not .Values.customServiceAccountName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeseal-webgui
  labels:
    {{- include "kubeseal-webgui.labels" . | nindent 4 }}
{{- with .Values.route.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}

