[tool.poetry]
name = "kubeseal-webgui-api"
version = "3.2.0"
description = "A python based backend for the kubeseal binary."
authors = ["Jan Herber <janherber@gmx.de>"]
license = "Apache-2.0"
readme = "README.md"
packages = [{include = "kubeseal_webgui_api"}]

[tool.poetry.dependencies]
python = "^3.9"
Jinja2 = "^3.1.2"
PyYAML = "^6.0"
kubernetes = "^24.2.0"
fastapi = "^0.85.0"
JSON-log-formatter = "^0.5.1"
uvicorn = "^0.19.0"
pydantic = "^1.10.2"

[tool.poetry.group.dev.dependencies]
black = "^22.8.0"
pytest = "^7.1.3"
isort = "^5.10.1"
flake8 = "^5.0.4"
pydocstyle = "^6.1.1"
pytest-cov = "^4.0.0"
pytest-flask = "^1.2.0"
flake8-awesome = "^1.3.0"
mypy = "^0.982"
pyupgrade = "^3.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
markers = ["cluster: marks test that requires a k8s cluster in their environment",
  "container: marks test that requires the container environment"]
