name: Run Python Playwright Tests
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd api
          pip install .

      - name: Install Playwright Browsers
        run: |
          cd api
          playwright install
      
      - name: Start Vue.js Development Server
        run: |
          cd ui
          npm install
          nohup npm run dev & 
          sleep 5

      - name: Run Playwright Tests
        run: |
          cd ui
          pytest tests/
